name    'desalvo-frontier'
version '0.1.1'
source 'https://github.com/desalvo/puppet-frontier'
author 'desalvo'
license 'Apache License, Version 2.0'
summary 'Puppet module for Frontier configuration'
description 'Puppet module for Frontier configuration'
project_page 'https://github.com/desalvo/puppet-frontier'
